// Code generated by entc, DO NOT EDIT.

package challenge

import (
	"time"
)

const (
	// Label holds the string label denoting the challenge type in the database.
	Label = "challenge"
	// FieldID holds the string denoting the id field in the database.
	FieldID          = "id"           // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt   = "created_at"   // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt   = "updated_at"   // FieldChallengeID holds the string denoting the challenge_id vertex property in the database.
	FieldChallengeID = "challenge_id" // FieldUserID holds the string denoting the user_id vertex property in the database.
	FieldUserID      = "user_id"      // FieldHuman holds the string denoting the human vertex property in the database.
	FieldHuman       = "human"        // FieldMagic holds the string denoting the magic vertex property in the database.
	FieldMagic       = "magic"        // FieldExpiresAt holds the string denoting the expires_at vertex property in the database.
	FieldExpiresAt   = "expires_at"

	// Table holds the table name of the challenge in the database.
	Table = "challenges"
)

// Columns holds all SQL columns for challenge fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldChallengeID,
	FieldUserID,
	FieldHuman,
	FieldMagic,
	FieldExpiresAt,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultExpiresAt holds the default value on creation for the expires_at field.
	DefaultExpiresAt func() time.Time
)
