// Code generated by entc, DO NOT EDIT.

package guild

import (
	"time"
)

const (
	// Label holds the string label denoting the guild type in the database.
	Label = "guild"
	// FieldID holds the string denoting the id field in the database.
	FieldID           = "id"         // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt    = "created_at" // FieldUpdatedAt holds the string denoting the updated_at vertex property in the database.
	FieldUpdatedAt    = "updated_at" // FieldSnowflake holds the string denoting the snowflake vertex property in the database.
	FieldSnowflake    = "snowflake"  // FieldMessage holds the string denoting the message vertex property in the database.
	FieldMessage      = "message"    // FieldCategories holds the string denoting the categories vertex property in the database.
	FieldCategories   = "categories" // FieldEntitlements holds the string denoting the entitlements vertex property in the database.
	FieldEntitlements = "entitlements"

	// Table holds the table name of the guild in the database.
	Table = "guilds"
)

// Columns holds all SQL columns for guild fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSnowflake,
	FieldMessage,
	FieldCategories,
	FieldEntitlements,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
)
